name: mkdocszh
on:
  workflow_dispatch:
  push:
    branches:
      - feature-947
    paths:
      - 'docs/**'
      - 'extension_root/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rm -rf arkid_extensions
      - uses: actions/checkout@v3
        with:
          repository: 'longguikeji/arkid-extensions'
          ref: 'v2.5-dev'
          path: 'arkid_extensions'
          token: '${{ secrets.NOTEVERY_TEST_TOKEN }}'
      - run: rm -rf arkid_extensions/com_longgui_app_protocol_saml2 arkid_extensions/com_longgui_auth_factor_saml2
      - run: ls arkid_extensions
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - run: pip install --disable-pip-version-check -r requirements.txt;
      - run: python manage.py migrate
      - run: mkdocs build -f docs/zh/mkdocs.yml -d site/zh
      - run: mkdocs build -f docs/en/mkdocs.yml -d site/en
      - run: cp -r docs/zh/site/zh/* docs/zh/site/
      - run: cp -r docs/en/site/en docs/zh/site/
      - name: push site to gh-pages branch
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
            GITHUB_TOKEN: ${{ secrets.NOTEVERY_TEST_TOKEN }}
        with:
            email: jiashuai@longguikeji.com
            build_dir: docs/zh/site
            branch: gh-pages
